<a href="https://colab.research.google.com/github/ImSumitJadhav/Machine-Learning/blob/main/T2_Feature_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/AlmaBetter/Project 2/SeoulBikeData.csv",encoding="latin1",usecols=["Seasons","Holiday","Functioning Day","Hour"])
df.head()

   Hour Seasons     Holiday Functioning Day
0     0  Winter  No Holiday             Yes
1     1  Winter  No Holiday             Yes
2     2  Winter  No Holiday             Yes
3     3  Winter  No Holiday             Yes
4     4  Winter  No Holiday             Yes

# **Feature Encoding**

# **1.One hot encoding**

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
# transforming the column after fitting
df1=df.copy()
ohe_df = ohe.fit_transform(df1[['Functioning Day']]).toarray()
ohe_df=pd.DataFrame(ohe_df)
df1=pd.concat([df1,ohe_df],axis=1)
df1.head()

   Hour Seasons     Holiday Functioning Day    0    1
0     0  Winter  No Holiday             Yes  0.0  1.0
1     1  Winter  No Holiday             Yes  0.0  1.0
2     2  Winter  No Holiday             Yes  0.0  1.0
3     3  Winter  No Holiday             Yes  0.0  1.0
4     4  Winter  No Holiday             Yes  0.0  1.0

# **2.get_dummies method**

In [32]:
import pandas as pd
df2=df.copy()
df2 = pd.get_dummies(df2, prefix=['yes',"yes"], columns=['Seasons','Holiday'])
df2.head(10)

,Hour,Functioning Day,yes_Autumn,yes_Spring,yes_Summer,yes_Winter,yes_Holiday,yes_No Holiday
0,0,Yes,0,0,0,1,0,1
1,1,Yes,0,0,0,1,0,1
2,2,Yes,0,0,0,1,0,1
3,3,Yes,0,0,0,1,0,1
4,4,Yes,0,0,0,1,0,1
5,5,Yes,0,0,0,1,0,1
6,6,Yes,0,0,0,1,0,1
7,7,Yes,0,0,0,1,0,1
8,8,Yes,0,0,0,1,0,1
9,9,Yes,0,0,0,1,0,1

# **3.Label Encoding**

In [54]:
df3=df.copy()

# labelEncoder present in scikitlearn library
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df3['Holiday'] = le.fit_transform(df3['Holiday'])

df3.tail(10)

      Hour Seasons  Holiday Functioning Day
8750    14  Autumn        1             Yes
8751    15  Autumn        1             Yes
8752    16  Autumn        1             Yes
8753    17  Autumn        1             Yes
8754    18  Autumn        1             Yes
8755    19  Autumn        1             Yes
8756    20  Autumn        1             Yes
8757    21  Autumn        1             Yes
8758    22  Autumn        1             Yes
8759    23  Autumn        1             Yes

# **4.OrdinalEncoder**

In [66]:
from sklearn.preprocessing import OrdinalEncoder
ord1 = OrdinalEncoder()

df4=df.copy()
# fitting encoder
oe_df=ord1.fit_transform(df4[['Seasons']])
oe_df=pd.DataFrame(oe_df,columns=["Season"])
df4=pd.concat([df4,oe_df],axis=1)
df4.head()

   Hour Seasons     Holiday Functioning Day  Season
0     0  Winter  No Holiday             Yes     3.0
1     1  Winter  No Holiday             Yes     3.0
2     2  Winter  No Holiday             Yes     3.0
3     3  Winter  No Holiday             Yes     3.0
4     4  Winter  No Holiday             Yes     3.0

# **5.Manually assigning ranking by using a dictionary**

In [68]:
df5=df.copy()

# creating a dictionary
sea_dict = {'Spring': 1, 'Autumn': 2, 'Summer': 3,'Winter':4}
# mapping values in column from dictionary
df5['new_season'] = df5.Seasons.map(sea_dict)
df5 = df5.drop(['Seasons'], axis=1)
df5.head()

   Hour     Holiday Functioning Day  new_season
0     0  No Holiday             Yes           4
1     1  No Holiday             Yes           4
2     2  No Holiday             Yes           4
3     3  No Holiday             Yes           4
4     4  No Holiday             Yes           4

# **6.Binary Encoder**

In [69]:
df6=df.copy()

from category_encoders import BinaryEncoder
encoder = BinaryEncoder(cols =['Holiday'])
# transforming the column after fitting
newdata = encoder.fit_transform(df6['Holiday'])
# concatenating dataframe
df6 = pd.concat([df6, newdata], axis = 1)
# dropping old column
df6 = df6.drop(['Holiday'], axis = 1)
df6.head(10)

   Hour Seasons Functioning Day  Holiday_0  Holiday_1
0     0  Winter             Yes          0          1
1     1  Winter             Yes          0          1
2     2  Winter             Yes          0          1
3     3  Winter             Yes          0          1
4     4  Winter             Yes          0          1
5     5  Winter             Yes          0          1
6     6  Winter             Yes          0          1
7     7  Winter             Yes          0          1
8     8  Winter             Yes          0          1
9     9  Winter             Yes          0          1

# **7.Hash Encoding**

In [74]:
df7=df.copy()

from sklearn.feature_extraction import FeatureHasher
# n_features contains the number of bits you want in your hash value.
h = FeatureHasher(n_features = 4, input_type ='string')
# transforming the column after fitting
hashed_Feature = h.fit_transform(df7['Holiday']).toarray()

df7 = pd.concat([df7, pd.DataFrame(hashed_Feature)], axis = 1)
df7.head()

   Hour Seasons     Holiday Functioning Day    0    1    2    3
0     0  Winter  No Holiday             Yes  2.0  0.0  2.0  2.0
1     1  Winter  No Holiday             Yes  2.0  0.0  2.0  2.0
2     2  Winter  No Holiday             Yes  2.0  0.0  2.0  2.0
3     3  Winter  No Holiday             Yes  2.0  0.0  2.0  2.0
4     4  Winter  No Holiday             Yes  2.0  0.0  2.0  2.0

# **8.Multilabel binerizer**

In [78]:
df8=df.copy()

from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
mlb_array=mlb.fit_transform(df8["Seasons"])
mlb_df=pd.DataFrame(mlb_array)
df8=pd.concat([df8,mlb_df],axis=1)
df8.head(10)

,Hour,Seasons,Holiday,Functioning Day,0,1,2,3,4,5,6,7,8,9,10,11
0,0,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
1,1,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
2,2,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
3,3,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
4,4,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
5,5,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
6,6,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
7,7,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
8,8,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0
9,9,Winter,No Holiday,Yes,0,0,1,1,0,1,0,1,0,1,1,0